flaskplate/__init__.py
from flaskplate.frontend.views import frontend

flaskplate/app.py
import os
import datetime
import logging
from logging.handlers import RotatingFileHandler

from flask import Flask, render_template

from flaskplate.frontend import frontend

from flaskplate.config import DefaultConfig

__all__ = ['create_app']

DEFAULT_BLUEPRINTS = (
    frontend,
)

def create_app(config=None, app_name=None, blueprints=None):
    """
    Create and configure the Flask app
    """
    if app_name is None:
        app_name = DefaultConfig.PROJECT
    if blueprints is None:
        blueprints = DEFAULT_BLUEPRINTS
    app = Flask(app_name,
                static_url_path='',
                instance_relative_config=True
               )
    configure_app(app, config)
    configure_template_processors(app)
    configure_blueprints(app, blueprints)
    configure_logging(app)
    configure_error_handlers(app)

    return app

def configure_app(app, config=None):
    # http://flask.pocoo.org/docs/api/#configuration
    app.config.from_object(DefaultConfig)

    if config is not None:
        app.config.from_object(config)


def configure_logging(app):

    if app.debug or app.testing:
        app.logger.setLevel(logging.DEBUG)
        # Skip debug and test mode. Just check standard output.
        return

    app.logger.setLevel(logging.INFO)

    info_log = os.path.join(app.config['LOG_FOLDER'], 'flaskplate.log')
    info_file_handler = RotatingFileHandler(info_log, maxBytes=100000, backupCount=10)
    info_file_handler.setLevel(logging.INFO)
    info_file_handler.setFormatter(logging.Formatter(
        '%(asctime)s %(levelname)s: %(message)s '
        '[in %(pathname)s:%(lineno)d]')
    )
    app.logger.addHandler(info_file_handler)


def configure_template_processors(app):

    @app.context_processor
    def my_processors():
        def now(format="%d-%m-%d %H:%M:%S"):
            return datetime.datetime.now().strftime(format)

        return dict(now=now)

def configure_blueprints(app, blueprints):

    for blueprint in blueprints:
        app.register_blueprint(blueprint)

def configure_error_handlers(app):

    @app.errorhandler(403)
    @app.errorhandler(401)
    def forbidden_page(error):
        return render_template("errors/403.html"), 403

    @app.errorhandler(404)
    def page_not_found(error):
        return render_template("errors/404.html"), 404

    @app.errorhandler(500)
    def server_error_page(error):
        return render_template("errors/500.html"), 500

flaskplate/frontend/__init__.py
from flaskplate.frontend.views import frontend

flaskplate/frontend/views.py
import logging
from flask import Blueprint, render_template, current_app

logger = logging.getLogger(__name__)

frontend = Blueprint('frontend', __name__)

@frontend.route('/')
def index():
    current_app.logger.debug('Do things here')
    return render_template('index.html')

@frontend.route('/help')
def help():
    current_app.logger.debug('Do things here')
    return render_template('frontend/footers/help.html', active="help")

flaskplate/templates/frontend/footers/help.html
{% extends 'layouts/base.html' %}

{% block body %}
<h2>Help</h2>

<p>Put some FAQ goodness here</p>
{% endblock %}

flaskplate/templates/index.html
{% extends 'layouts/base.html' %}

{% set page_title = 'Home' %}

{% block container %}
<div class="container">
    <div class="hero-unit">
        <h1>Flaskplate</h1>
        <p>If you are seeing this, congrats!</p>
    </div>
</div>
{% endblock %}

flaskplate/templates/layouts/base.html
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>{% block title %}{{ page_title|default('Flaskplate') }}{% endblock %} </title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- Place favicon.ico and apple-touch-icon.png in the root directory -->
    <link rel="Shortcut Icon" href="{{ url_for('static', filename='favicon.png') }}" type="image/x-icon">

    {% block css %}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/normalize.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}">
    {% endblock %}

    {% block css_style %}
    {% endblock %}

    {% block js_top %}
    <script src="//upcdn.b0.upaiyun.com/libs/modernizr/modernizr-2.6.2.min.js"></script>
    {% endblock %}
</head>
<body>

    <div id='wrap'>
        {% block topbar %}
        <div class="navbar">
            <div class="navbar-inner">
                <div class="container">
                    <a class='brand' href='{{ url_for('frontend.index') }}'><img src="{{ url_for('static', filename='img/logo.png') }}" height="80px" width="80px" /></a>

                    <div class="nav-collapse collapse pull-right">
                      <ul class="nav">
                        <!-- nav items go here -->
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        {% endblock %}

        {% block flash_message %}
            {% with messages = get_flashed_messages(with_categories=True) %}
                {% if messages %}
                <div class="container">
                    <div id='flash_message_container'>
                        {% for category, msg in messages %}
                            <div class="alert alert-{{ category }}">
                                <button type="button" class="close" data-dismiss="alert">×</button>
                                {{ msg }}
                            </div>
                        {% endfor %}
                    </div>
                </div>
                {% endif %}
            {% endwith %}
        {% endblock %}

        {% block container %}
        <div class="container">

            {% block top %}
                {% if tabs %}
                <div>
                    <ul class="nav nav-tabs">
                        {% for tab, link in tabs %}
                        <li class="{% if active == tab %}active{% endif %}">
                            <a href="{{ link }}">{{ tab|capitalize }}</a>
                        </li>
                        {% endfor %}
                    </ul>
                </div>
                {% endif %}
            {% endblock %}

            {% block body %}
            {% endblock %}

        </div>
        {% endblock %}
        <div id="push"></div>
    </div>

    <footer id="footer">
        <ul class="footer-links">
          <li>© {{ now('%Y') }}</li>
            <li><a href='http://www.craftsy.com/'>Craftsy</a></li>
            <li class="muted">&middot;</li>
        </ul>
    </footer>

    {% block js_btm %}
    <script src="//upcdn.b0.upaiyun.com/libs/jquery/jquery-2.0.0.min.js"></script>
    {% endblock %}

</body>
</html>